const NotificationType = {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    INFO: "INFO",
    WARNING: "WARNING",

    FILE_UPLOAD: "FILE_UPLOAD",
    FILE_DOWNLOAD: "FILE_DOWNLOAD",
    FILE_UPLOAD_SUCCESS: "FILE_UPLOAD_SUCCESS",
    FILE_DOWNLOAD_SUCCESS: "FILE_DOWNLOAD_SUCCESS",
    FILE_UPLOAD_FAILURE: "FILE_UPLOAD_FAILURE",
    FILE_DOWNLOAD_FAILURE: "FILE_DOWNLOAD_FAILURE",

    FILE_ENCRYPTION: "FILE_ENCRYPTION",
    FILE_ENCRYPTION_FAILURE: "FILE_ENCRYPTION_FAILURE",

    FILE_DECRYPTION: "FILE_DECRYPTION",
    FILE_DECRYPTION_FAILURE: "FILE_DECRYPTION_FAILURE",

    NETWORK_ERROR: "NETWORK_ERROR"
}

export { NotificationType };